name: Sync Comments & Likes

on:
  schedule:
    - cron: "*/30 * * * *"
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.ACCESS_GITHUB_TOKEN }} # use PAT here

      - name: Debug repo
        run: |
          pwd
          ls -la

      - name: Debug Node version
        run: |
          node -v
          npm -v

      - uses: actions/setup-node@v4
        with:
          node-version: 16

      - name: Install deps
        run: npm install

      - name: Fetch issue data
        run: npm run fetch-all
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_GITHUB_TOKEN }}

      - name: Update last sync badge
        run: |
          mkdir -p source/_data
          echo '{
            "schemaVersion": 1,
            "label": "Last Sync",
            "message": "'"$(TZ="Asia/Taipei" date +"%Y-%m-%d %H:%M %Z")"'",
            "color": "brightgreen"
          }' > source/_data/sync-status.json

      - name: Commit updated JSON
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add source/_data/sync-status.json
          git commit -m "Update last sync time" || echo "No changes to commit"
          git push origin HEAD:${{ github.ref }}
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_GITHUB_TOKEN }}

      - name: Build
        run: npx hexo generate

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.ACCESS_GITHUB_TOKEN }}
          publish_dir: ./public
